version: '3'

services:
  coder_server:
    container_name: code-server
    image: ghcr.io/linuxserver/code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_Yrok
      - PASSWORD=password #optional
      - SUDO_PASSWORD=password #optional
      - SUDO_PASSWORD_HASH=password #optional
      - PROXY_DOMAIN=code-server.my.domain #optional
    volumes:
      - ./config:/config
    ports:
      - 8443:8443
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certs:/etc/nginx/certs
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    links:
      - coder_server
    restart: unless-stopped
